config/routes.rb
Rails.application.routes.draw do

  
  root 'basics#index'

  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  namespace :users do
    resources :users
  end

  namespace :admin do
    resources :sellers
  end

  get '/valentine', to: 'valentine#new'
  post '/valentine', to: 'valentine#calc'
  
end

app/views/elements/menu/clear.haml
.top_menu
	.ui.column.grid
		.column
			%a.centered{href: url_for('/users/sign_in')}
				%span.sans.blue.color
					SOFT
				%span.color.white.b3.sans.relative{style: 'left: -2px'}
					ENCONDER

app/views/elements/menu/menu.haml
.top_menu
	.ui.three.column.grid
		.column

			=# left menu
			.ui.segment.no.margin.padding.bg.right.aligned
				.ui.dropdown.hover.pointing.left.top.large.icon
					%i.icon.big.ellipsis.vertical.link.blue

					.menu
						%a.item{:href=>"#{url_for('/admin/sellers')}"}
							%i.icon.large.building
							%span.b2
								Vendedores
							%span.mini.text.smooth.color.sans.b2
								&nbsp;
								= Admin::Seller.count

						%a.item{:href=>"#{url_for('/users/users')}"}
							%i.icon.large.payment
							%span.b2
								Usuários
							%span.mini.text.smooth.color.sans.b2
								&nbsp;
								= User.count

						%a.item{:href=>"#{url_for('/')}"}
							%i.icon.large.home
							%span.b2
								Página Inicial

		.column
			.centered
				%span.sans.blue.color
					SOFT
				%span.color.white.b3.sans.relative{style: 'left: -2px'}
					ENCONDER

		.column

			=# right menu
			.ui.segment.no.margin.padding.bg.left.aligned
				.ui.inline.dropdown.hover.right.top.pointing.large.icon
					%i.icon.large.user.link.green

					.menu
						%a.item{:href=>"#{url_for(edit_user_registration_path)}"}
							%i.icon.large.user
							%span Meu Perfil

						%a.item{:href=>"#{url_for(users_users_path)}"}
							%i.icon.large.users
							%span Usuários

						%a.item{:href=> destroy_user_session_path, :'data-method' => 'DELETE'}
							%i.icon.large.log.out
							%span Sair