config/routes.rb
Rails.application.routes.draw do

  
  root 'basics#index'

  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  namespace :users do
    resources :users
  end

  namespace :admin do
    resources :sellers
  end

  get '/valentine', to: 'valentine#new'
  post '/valentine', to: 'valentine#calc'
  
end

app/models/admin/seller.rb
class Admin::Seller < ActiveRecord::Base
end

app/controllers/admin/sellers_controller.rb
class Admin::SellersController < ApplicationController
  before_action :set_admin_seller, only: [:show, :edit, :update, :destroy]

  # GET /admin/sellers
  # GET /admin/sellers.json
  def index
    @admin_sellers = Admin::Seller.all
  end

  # GET /admin/sellers/1
  # GET /admin/sellers/1.json
  def show
  end

  # GET /admin/sellers/new
  def new
    @admin_seller = Admin::Seller.new
  end

  # GET /admin/sellers/1/edit
  def edit
  end

  # POST /admin/sellers
  # POST /admin/sellers.json
  def create
    @admin_seller = Admin::Seller.new(admin_seller_params)

    respond_to do |format|
      if @admin_seller.save
        format.html { redirect_to @admin_seller, notice: 'Seller was successfully created.' }
        format.json { render :show, status: :created, location: @admin_seller }
      else
        format.html { render :new }
        format.json { render json: @admin_seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/sellers/1
  # PATCH/PUT /admin/sellers/1.json
  def update
    respond_to do |format|
      if @admin_seller.update(admin_seller_params)
        format.html { redirect_to @admin_seller, notice: 'Seller was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_seller }
      else
        format.html { render :edit }
        format.json { render json: @admin_seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/sellers/1
  # DELETE /admin/sellers/1.json
  def destroy
    @admin_seller.destroy
    respond_to do |format|
      format.html { redirect_to admin_sellers_url, notice: 'Seller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_seller
      @admin_seller = Admin::Seller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_seller_params
      params.require(:admin_seller).permit(:name, :corporate, :cnpj)
    end
end

app/helpers/admin/sellers_helper.rb
module Admin::SellersHelper
end

app/views/admin/sellers/_form.html.erb
<%= form_for(@admin_seller) do |f| %>
  <% if @admin_seller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_seller.errors.count, "error") %> prohibited this admin_seller from being saved:</h2>

      <ul>
      <% @admin_seller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :corporate %><br>
    <%= f.text_field :corporate %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br>
    <%= f.text_field :cnpj %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/sellers/edit.html.erb
<h1>Editing Admin Seller</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_seller %> |
<%= link_to 'Back', admin_sellers_path %>

app/views/admin/sellers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Sellers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Corporate</th>
      <th>Cnpj</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_sellers.each do |admin_seller| %>
      <tr>
        <td><%= admin_seller.name %></td>
        <td><%= admin_seller.corporate %></td>
        <td><%= admin_seller.cnpj %></td>
        <td><%= link_to 'Show', admin_seller %></td>
        <td><%= link_to 'Edit', edit_admin_seller_path(admin_seller) %></td>
        <td><%= link_to 'Destroy', admin_seller, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Seller', new_admin_seller_path %>

app/views/admin/sellers/new.html.erb
<h1>New Admin Seller</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_sellers_path %>

app/views/admin/sellers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_seller.name %>
</p>

<p>
  <strong>Corporate:</strong>
  <%= @admin_seller.corporate %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @admin_seller.cnpj %>
</p>

<%= link_to 'Edit', edit_admin_seller_path(@admin_seller) %> |
<%= link_to 'Back', admin_sellers_path %>