config/routes.rb
Rails.application.routes.draw do

  
  root 'basics#index'

  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks'
  }

  namespace :users do
    resources :users
  end

  namespace :admin do
    resources :sellers
  end

  get '/valentine', to: 'valentine#new'
  post '/valentine', to: 'valentine#calc'
  
end

app/models/user.rb
class User < ActiveRecord::Base

	# Deixando maíusculo/mínusculo alguns valores do registro
  	before_save {
  		|user| user.name = user.name.upcase
  	}

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	# devise:database_authenticatable, :recoverable, :rememberable,
	#		:trackable, :confirmable, :lockable, :registerable, :validatable

	devise 	:database_authenticatable, :registerable,
	        :recoverable, :rememberable, :trackable, :validatable, 
	        :confirmable, :lockable, :timeoutable

	# paperclip, photo user management
	# attr_accessible :avatar
	has_attached_file 	:avatar, styles: { :medium => '300x300>', :thumb => '100x100>' }, 
						default_url: 'devise_default_avatar.png'
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	# verificar se existe um registro com um determinado
	# token. contexto representa qual ação o usuário está
	# tomando, como :reset_password_token, :confirmation_token
	def self.valid_token token, context
	  	return User.exists?(:"#{context}"=> Devise.token_generator.digest(User, context, token))
	end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

  layout 'no_menu', only: [:new, :create, :show]

  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

  layout 'no_menu', only: [:new, :edit, :update, :create]

  # GET /resource/password/new
  # def new
  #  super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit

    # verificando se o token para resetar o password é válido
    if (!User.valid_token(params['reset_password_token'], :reset_password_token))
      message = t('.invalid_token')
      message[':url'] = url_for new_user_password_path
      flash[:warning] = message

      redirect_to new_user_session_path
    end

    super
  end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for resource_name
    flash[:success] = t 'devise.confirmations.change_password_instructions'

    super resource_name
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  layout 'no_menu', only: [:new]

  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:edit]

  # before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << [:name, :avatar]
  end

  # You can put the params you want to permit in the empty array.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << [:name, :avatar]
  end

  # The path used after sign up.
  # def after_sign_up_path_for resource
  #  super user_session_path
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for resource
    flash[:info] = t 'devise.confirmations.send_instructions'
    user_session_path
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  self.layout 'no_menu'
  # before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController

  layout 'no_menu', only: [:new, :create]
  
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController

  def index
    @users = User.paginate(:page => params[:page], :per_page => 10).order(:id)
  end
  
  def new
    @user = User.new
  end

  def show
    @user = User.find params[:id]
  end
  
  def edit
    @user = User.find params[:id]
  end
  
  def create
    @user = User.new user_params
      
    if @user.save
      flash[:success] = 'Usuário criado com sucesso.'
      redirect_to user_path(@user)
    else
      render :action => 'new'
    end
  end
  
  def update
    @user = User.find params[:id]
    
    if @user.update_attributes(user_params)
      flash[:success] = 'Edição efetuada com sucesso.'
      redirect_to user_path(@user)
    else
      render :action => 'edit'  
    end
  end
  
  def destroy
    flash[:success] = 'Deletação efetuada com sucesso.'
    (User.find params[:id]).destroy
    redirect_to users_users_path
  end
  
  private
  
  def user_params
    params.require(:user).permit(:avatar, :name, :email, :pass, :pass_confirmation)
  end

end

app/views/users/partial/_form.haml
= form_for(resource, url: registration_path(resource_name), html: {class: 'ui form'}) do |f|

  .title
    .ui.header.aligned.center
    = image_tag @user.avatar.url(:thumb), class: 'ui image circular centered tiny'

  %div{style: 'padding: 25px;'}        
    .field
      = f.label :avatar, 'Selecione uma foto:', class: 'smooth color text left sans b'
      = f.file_field :avatar
      = form_message resource, :avatar

    %br

    .field
      = f.text_field :name, placeholder: 'Nome', autofocus: true, class: 'text upper'
      = form_message resource, :name

    .field
      = f.email_field :email, placeholder: 'E-mail', class: 'text lower'
      = form_message resource, :email

    .field
      = f.password_field :password, placeholder: 'Senha'
      = form_message resource, :password

    .field
      = f.password_field :password_confirmation, placeholder: 'Confirme sua senha'
      = form_message resource, :password_confirmation

    .ui.segment.basic.right.aligned.no.padding
      %button.ui.button.green.large.icon
        %i.icon.checkmark.relative{style: 'top: -1px;'}

app/views/users/partial/_menu.haml
- if !defined? options
	- options = [:sign_in, :sign_up, :forgot_password, :confirmation, :block]

.ui.dropdown.hover.pointing.right.bottom.options.large.icon.fixed{:style=>'bottom: 7%; right: 2.5%;'}
	%i.icon.big.ellipsis.vertical.link

	.menu
		- if options.include?(:block)
			%a.item{:href=>"#{url_for(new_user_unlock_path)}"}
				%i.icon.large.lock
				%span.b2
					Desbloqueio de conta

		- if options.include?(:confirmation)
			%a.item{:href=>"#{url_for(new_user_confirmation_path)}"}
				%i.icon.large.check
				%span.b2
					Confirmação de conta

		- if options.include?(:forgot_password)
			%a.item{:href=>"#{url_for(new_user_password_path)}"}
				%i.icon.large.help
				%span.b2
					Esqueci minha senha

		- if options.include?(:sign_up)
			%a.item{:href=>"#{url_for(new_user_registration_path)}", class: 'bg green'}
				%i.icon.large.plus
				%span.b2
					Cadastre-se

		- if options.include?(:sign_in)
			%a.item{:href=>"#{url_for(new_user_session_path)}"}
				%i.icon.large.sign.in
				%span.b2
					Conecte-se